name: Publish workflow
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  discover-versions:
    name: Discover versions
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Find v* folders and create matrix
        id: set-matrix
        run: |
          folders=$(ls -d v*/ | sed 's#/##' | jq -R -s -c 'split("\n")[:-1]')
          echo "Detected versions: $folders"
          echo "matrix=$folders" >> "$GITHUB_OUTPUT"

  build:
    name: Build versions
    needs: discover-versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ${{ fromJson(needs.discover-versions.outputs.versions) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.version }}
          file: ./${{ matrix.version }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8,linux/s390x
          tags: |
            ghcr.io/${{ github.repository_owner }}/paper-server-${{ matrix.version }}:latest